[project]
name = "guardian-vault"
description = "sBTC Guardian Vault: spending rules, social recovery, inheritance"
authors = ["kamikaiten.base.eth"] 
telemetry = false

[contracts.vault]
path = "contracts/vault.clar"

[contracts.guardians]
path = "contracts/guardians.clar"

[contracts.recovery]
path = "contracts/recovery.clar"

[contracts.policy]
path = "contracts/policy.clar"

[contracts.errors]
path = "contracts/errors.clar"

[contracts.sip010-ft-trait]
path = "contracts/traits/sip010-ft-trait.clar"
